
#  jackson:
#    property-naming-strategy: SNAKE_CASE

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
  pattern:
    console: "%d %-5level %logger : %msg%n"