spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cdmdev.cengda8pesbb.us-east-1.rds.amazonaws.com:3306/CDMDEV
    username: CDMDB
    password: Admin$123
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        show-sql: true
#        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.web: ERROR

customer:
  id:
    fetch: CUS

